apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-webhook-cfg
  labels:
    app: env-injector
webhooks:
  - name: env-injector.hardt.io
    clientConfig:
      service:
        name: env-injector-webhook-svc
        namespace: default
        path: "/mutating-pods"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        env-injector: enabled
