apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-webhook-cfg
  labels:
    app: env-injector
webhooks:
  - name: env-injector.hardt.io
    clientConfig:
      service:
        name: env-injector-webhook-svc
        namespace: ps-env-inject
        path: "/mutating-pods"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lVTlBkY0Y0ZldvMHowOHMxWnh2ZXE4aGdQYUFRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUF4TUNZMkV3SGhjTk1Ua3dPREEyTWpBME5ESXhXaGNOTWpNd09EQTJNakEwTkRJeApXakFOTVFzd0NRWURWUVFERXdKallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFNRlNzejdkbHR0dytFV2xobXRYRVZ0cFhIejg4ZVk1NU00SEZtM3lFSk5KTDNNTmRuVkRjV1hwc0t6dVByTUMKKy9jL29rZVl6RVh0ZDNkd3U3TktrcTh0NTdselBNbkE4bW8yZ05VZlJuTis1N3ZMYjVCOUZ2Z1JWUkNPeDZuSgpKTkdjSlNKQTliN2F6QlZkZ2NXclFBSE5ReE1iSENKQktKNkJ1YjNtQUdSSmdjdTBGK1hleXE5TWtRZ0tSVXBMCnpCSEJjcEJrZVFVOVkxNDh1OWZnNVhoQ056am5oRFZjSmJsKytwcnQrNlVDdmlreFdadkRCbFV5SEtDK1UwTDEKMHpqb1NuNjNJRW84MTNVMHVsQkJpM1ViWFlzMzV5L2V1alZSY1B4YkdLMnE2eEE1MVRoMFR4WjVLY3NPZmY4ZgpqUUFoRUJjQkNQN0lkYUVQYnBaSVVuY0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGSjJiMDBjcUVJUXh5aEY0CmNGNnpueXlxTmZQa01COEdBMVVkSXdRWU1CYUFGSjJiMDBjcUVJUXh5aEY0Y0Y2em55eXFOZlBrTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKR0hxR2pzTUtVVzZVWWNjMGxlc2pxVQpuS2ZrR3VrUEE1ZzBvK0ovckpSdDRNRkJXN2Y2ei9kMS8wN004c29OK0gvUnhkRVBzeVZQRjMzWG5zb29LVXJaCm5DWGduUTgyVzQwc2dqOWJHZHhhc1Jqb1l1Q1pSTU5JbVNJRDJWSEpjVkVERlorLzJFTngvWmQvRzVGT1RRbUUKMXlZSUZ6S1htL0RKRmM3WHBKUmpWSE0wRmdsNzMwMEx0Ukh6dFhhSmtlYzUrTDROenBuZmFEemhlUm1YQVNuWgovN3RQYURjQ0FtcHorZjloeGlDTzF0ZktPQWxRMXB1KzlBTkdYRDh1c1lkWTlYWjJzNkVIaGNEVWhVR3VZUGhRCmxLNndKKzRhRVF3MW1oTG5kdnl6S0dITWxMZGkwazBCeEowRlZFUXRpZExCVmZIbVAvWExiUURlaSt0MEllUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
#    namespaceSelector:
#      matchLabels:
#        env-injector: enabled
