apiVersion: v1
kind: Service
metadata:
  name: env-injector-webhook-svc
  namespace: ps-env-inject
  labels:
    app: env-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: env-injector
