kind: ConfigMap
apiVersion: v1
metadata:
  name: signing-ca
  namespace: kube-system
data:
  client-ca-file: |-
    -----BEGIN CERTIFICATE-----
    MIIC+zCCAeOgAwIBAgIUNPdcF4fWo0z08s1Zxveq8hgPaAQwDQYJKoZIhvcNAQEL
    BQAwDTELMAkGA1UEAxMCY2EwHhcNMTkwODA2MjA0NDIxWhcNMjMwODA2MjA0NDIx
    WjANMQswCQYDVQQDEwJjYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AMFSsz7dlttw+EWlhmtXEVtpXHz88eY55M4HFm3yEJNJL3MNdnVDcWXpsKzuPrMC
    +/c/okeYzEXtd3dwu7NKkq8t57lzPMnA8mo2gNUfRnN+57vLb5B9FvgRVRCOx6nJ
    JNGcJSJA9b7azBVdgcWrQAHNQxMbHCJBKJ6Bub3mAGRJgcu0F+Xeyq9MkQgKRUpL
    zBHBcpBkeQU9Y148u9fg5XhCNzjnhDVcJbl++prt+6UCvikxWZvDBlUyHKC+U0L1
    0zjoSn63IEo813U0ulBBi3UbXYs35y/eujVRcPxbGK2q6xA51Th0TxZ5KcsOff8f
    jQAhEBcBCP7IdaEPbpZIUncCAwEAAaNTMFEwHQYDVR0OBBYEFJ2b00cqEIQxyhF4
    cF6znyyqNfPkMB8GA1UdIwQYMBaAFJ2b00cqEIQxyhF4cF6znyyqNfPkMA8GA1Ud
    EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJGHqGjsMKUW6UYcc0lesjqU
    nKfkGukPA5g0o+J/rJRt4MFBW7f6z/d1/07M8soN+H/RxdEPsyVPF33XnsooKUrZ
    nCXgnQ82W40sgj9bGdxasRjoYuCZRMNImSID2VHJcVEDFZ+/2ENx/Zd/G5FOTQmE
    1yYIFzKXm/DJFc7XpJRjVHM0Fgl7300LtRHztXaJkec5+L4NzpnfaDzheRmXASnZ
    /7tPaDcCAmpz+f9hxiCO1tfKOAlQ1pu+9ANGXD8usYdY9XZ2s6EHhcDUhUGuYPhQ
    lK6wJ+4aEQw1mhLndvyzKGHMlLdi0k0BxJ0FVEQtidLBVfHmP/XLbQDei+t0IeQ=
    -----END CERTIFICATE-----